In [1]:
import numpy as np
np.__version__

'1.16.2'

In [5]:
np? # built in documentation

In [6]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 1, 2, 4])

array([3.14, 1.  , 2.  , 4.  ])

In [8]:
np.array([3.14, 1,2,4], dtype='float32')

array([3.14, 1.  , 2.  , 4.  ], dtype=float32)

In [10]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# create 3x5 array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping y 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2,)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
# Create a 3x3 array of normally distributed values with mean 0 and std = 1
np.random.normal(0, 1, (3, 3))

array([[ 0.76142956,  0.01606072,  0.58464694],
       [-0.36336795,  0.74334991, -0.73609569],
       [ 0.29863563,  0.13118646,  0.45934527]])

In [21]:
np.random.normal?

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3,3))

array([[8, 7, 8],
       [1, 7, 4],
       [8, 5, 0]])

In [25]:
# create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# Basics of NumPy Arrays